# CONFIGURATION
variables:
  IMAGE_NAME: 'oss-benchmark-api'
  IMAGE_TAGS: '$CI_COMMIT_SHA latest'
  DOCKERFILE_PATH: '.'

include:
  - project: 'digital-sustainability-lab/ci-lib'
    ref: main
    file:
      - 'templates/dsl_build_simple.yml'

