name: Compile Github Data from Institutions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: populate keys.json
      run: echo "{\"token\":\"${GITHUBTOKEN}\"}" > keys.json
    - name: run
      run: |
        python3 OSS_github_benchmark.py