name: Test input data

on:
  push:
    paths:
    - oss-api/src/data-gathering/github_repos.json

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: lint data
      run: |
        python -mjson.tool oss-api/src/data-gathering/github_repos.json
